In [5]:
# Import all libraries which is related to your output
import pandas as pd # pandas we use for read the output
from sklearn.tree import DecisionTreeClassifier # scrikit-learn library used in machine learning
# and it draw decision tree and how to tree make decison as per your output

In [6]:
# Create own dataset and variable name = data

data = {
    "Weather": [
        "Sunny", "Cloudy", "Sunny", "Cloudy", "Rainy",
        "Rainy", "Rainy", "Sunny", "Cloudy", "Rainy"
    ],
    "Temperature": [
        "Hot", "Hot", "Mild", "Mild", "Mild",
        "Cool", "Cool", "Hot", "Mild", "Mild"
    ],
    "Humidity": [
        "High", "High", "Normal", "High", "High",
        "Normal", "Normal", "High", "Normal", "High"
    ],
    "Wind": [
        "Weak", "Weak", "Strong", "Strong", "Strong",
        "Strong", "Weak", "Weak", "Weak", "Strong"
    ],
    "Play": [
        "No", "Yes", "Yes", "Yes", "No",
        "No", "Yes", "No", "Yes", "No"
    ]
}

In [7]:
# DataFrame represents data in rows and columns

df = pd.DataFrame(data)
df

  Weather Temperature Humidity    Wind Play
0   Sunny         Hot     High    Weak   No
1  Cloudy         Hot     High    Weak  Yes
2   Sunny        Mild   Normal  Strong  Yes
3  Cloudy        Mild     High  Strong  Yes
4   Rainy        Mild     High  Strong   No
5   Rainy        Cool   Normal  Strong   No
6   Rainy        Cool   Normal    Weak  Yes
7   Sunny         Hot     High    Weak   No
8  Cloudy        Mild   Normal    Weak  Yes
9   Rainy        Mild     High  Strong   No

In [12]:
#convert text data yo numebric data becuause machine can't understand ur text data
#this all process name is label encoding
#replace means text to numebric
df_encoded = df.replace({
    "Sunny": 0,"Cloudy": 1,"Rainy": 2,
    "Hot": 0,"Mild": 1,"Cool": 2,
    "High": 0,"Normal": 1,
    "Weak": 0,"Strong": 1,
    "No": 0,"Yes": 1
})

/tmp/ipykernel_13384/521691602.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_encoded = df.replace({

In [11]:
df_encoded #for print ypur data

   Weather  Temperature  Humidity  Wind  Play
0        0            0         0     0     0
1        1            0         0     0     1
2        0            1         1     1     1
3        1            1         0     1     1
4        2            1         0     1     0
5        2            2         1     1     0
6        2            2         1     0     1
7        0            0         0     0     0
8        1            1         1     0     1
9        2            1         0     1     0

In [15]:

# Separate input and output

X = df_encoded.drop("Play", axis=1)
# Here we drop the Play attribute.
# axis=1 means remove column, not row.

y = df_encoded["Play"]
# Here we use the Play attribute as y (output).

X

   Weather  Temperature  Humidity  Wind
0        0            0         0     0
1        1            0         0     0
2        0            1         1     1
3        1            1         0     1
4        2            1         0     1
5        2            2         1     1
6        2            2         1     0
7        0            0         0     0
8        1            1         1     0
9        2            1         0     1

In [17]:
X

   Weather  Temperature  Humidity  Wind
0        0            0         0     0
1        1            0         0     0
2        0            1         1     1
3        1            1         0     1
4        2            1         0     1
5        2            2         1     1
6        2            2         1     0
7        0            0         0     0
8        1            1         1     0
9        2            1         0     1

In [14]:
y

0     No
1    Yes
2    Yes
3    Yes
4     No
5     No
6    Yes
7     No
8    Yes
9     No
Name: Play, dtype: object

In [18]:

# Train Decision Tree model

model = DecisionTreeClassifier()

model.fit(X, y)

# X = Weather, Temperature, Humidity, Wind
# y = output labels

DecisionTreeClassifier()

In [19]:

print("\n Model Trained ")

# It shows your model is trained for prediction
# because you fit the model using X and y

 Model Trained

In [20]:

# Make a sample prediction

sample = [[1, 1, 0, 0]] #here u can create ur own sample data for prediction

prediction = model.predict(sample)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [21]:

if prediction[0] == 1:
    result = "Play"
else:
    result = "Don't Play"

print(result)

Play