In [1]:
# Import Libraries
import pandas as pd

In [3]:
# Create your data
data = {
    'Age': ['Youth', 'Youth', 'Middle', 'Senior', 'Senior',
            'Middle', 'Senior', 'Youth', 'Youth', 'Senior'],
    'Income': ['High', 'High', 'High', 'Medium', 'Low',
               'Low', 'Low', 'Medium', 'Low', 'Medium'],
    'Student': ['No', 'No', 'No', 'No', 'Yes',
                'Yes', 'Yes', 'No', 'Yes', 'Yes'],
    'Creditrating': ['Fair', 'Excellent', 'Fair', 'Fair', 'Fair',
                     'Excellent', 'Excellent', 'Fair', 'Fair', 'Fair'],
    'Buyscomputer': ['No', 'No', 'Yes', 'Yes', 'Yes',
                     'No', 'Yes', 'No', 'Yes', 'Yes']
}

In [4]:
# Print all data using pandas
df = pd.DataFrame(data)
df

      Age  Income Student Creditrating Buyscomputer
0   Youth    High      No         Fair           No
1   Youth    High      No    Excellent           No
2  Middle    High      No         Fair          Yes
3  Senior  Medium      No         Fair          Yes
4  Senior     Low     Yes         Fair          Yes
5  Middle     Low     Yes    Excellent           No
6  Senior     Low     Yes    Excellent          Yes
7   Youth  Medium      No         Fair           No
8   Youth     Low     Yes         Fair          Yes
9  Senior  Medium     Yes         Fair          Yes

In [5]:
# now and convert categorical to numberical (label encoding)

from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for column in df.columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

In [6]:
# Split Features & Target

X = df.drop('Buyscomputer', axis=1)  # Features
y = df['Buyscomputer']               # Target

In [7]:
X

   Age  Income  Student  Creditrating
0    2       0        0             1
1    2       0        0             0
2    0       0        0             1
3    1       2        0             1
4    1       1        1             1
5    0       1        1             0
6    1       1        1             0
7    2       2        0             1
8    2       1        1             1
9    1       2        1             1

In [8]:
y

0    0
1    0
2    1
3    1
4    1
5    0
6    1
7    0
8    1
9    1
Name: Buyscomputer, dtype: int64

In [9]:

# Apply KNN Algorithm

from sklearn.neighbors import KNeighborsClassifier

# Create model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X, y)

KNeighborsClassifier()

In [10]:

print('now model is trained')

now model is trained

In [11]:

new_data = pd.DataFrame({
    'Age': ['Youth'],
    'Income': ['Medium'],
    'Student': ['Yes'],
    'Creditrating': ['Fair']
})

In [12]:

# Loop of each column
for col in new_data.columns:
    new_data[col] = label_encoders[col].transform(new_data[col])

In [13]:

# ----- Predict using trained KNN model -----
prediction = knn.predict(new_data)
prediction

array([1])

In [14]:

# Decode your prediction to original label

final_result = label_encoders['Buyscomputer'].inverse_transform(prediction)

print("""Predicted class (encoded):
Please check the `Buyscomputer` to verify if it is correct.""", prediction)

print("""Predicted class (actual):
Please check the `Buyscomputer` to verify if it is correct.""", final_result[0])

Predicted class (encoded):
Please check the `Buyscomputer` to verify if it is correct. [1]
Predicted class (actual):
Please check the `Buyscomputer` to verify if it is correct. Yes